const CLIENT_ID = '540f2aed8bcf4f74b9349bb7deeb4f04';
const REDIRECT_URI = 'http://localhost:3000/';
let accessToken = '';
let expirationTime = '';

const Spotify = {
  getAccessToken() {
    let accessTokenFromURL = window.location.href.match(/access_token=([^&]*)/);
    let expirationTimeFromURL = window.location.href.match(/expires_in=([^&]*)/);

    if (accessToken) {
      return accessToken;
    } else if (accessTokenFromURL && expirationTimeFromURL) {
      accessToken = accessTokenFromURL[1];
      let expirationTime = expirationTimeFromURL[1];

      window.setTimeout(() => accessToken = '', expirationTime * 1000);
      window.history.pushState('Access Token', null, '/');

      return accessToken;
    } else if (!accessToken && !accessTokenFromURL) {
      window.location = `https://accounts.spotify.com/authorize?client_id=${CLIENT_ID}&response_type=token&scope=playlist-modify-public&redirect_uri=${REDIRECT_URI}`;
    }
  },

  async search(input) {
    try {
      let body = {
        headers: {
          Authorization: `Bearer ${this.getAccessToken()}`
        }
      };

      const response = await fetch(`https://api.spotify.com/v1/search?type=track&q=${input}`, body);

      if (response.ok) {
        const jsonResponse = await response.json();
        if (jsonResponse.tracks.items.length > 0) {
          console.log(jsonResponse);
          return jsonResponse.tracks.items
        } else {
          return [];
        }
      }

      throw new Error('Request failed!');
    } catch (error) {
      console.log(error);
    }
  }
}

// const Spotify = JSON.parse(`{
//   "tracks": {
//     "href": "https://api.spotify.com/v1/search?query=pink+floyd&type=track&market=US&offset=0&limit=10",
//     "items": [
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/0bCAjiUamIFqKJsekOYuRw"
//           },
//           "href": "https://api.spotify.com/v1/albums/0bCAjiUamIFqKJsekOYuRw",
//           "id": "0bCAjiUamIFqKJsekOYuRw",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/4e9c7731373ba52446f4de7f5d0af6c51007f6fc",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/aab31a87e274822dd11c1de4b6e851aa3a471500",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/5f85b9e99c486a02f53fa9f43d0c152cccd49af6",
//               "width": 64
//             }
//           ],
//           "name": "Wish You Were Here",
//           "release_date": "1975-09-12",
//           "release_date_precision": "day",
//           "total_tracks": 5,
//           "type": "album",
//           "uri": "spotify:album:0bCAjiUamIFqKJsekOYuRw"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 334743,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100088"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/6mFkJmJqdDVQ1REhVfGgd1"
//         },
//         "href": "https://api.spotify.com/v1/tracks/6mFkJmJqdDVQ1REhVfGgd1",
//         "id": "6mFkJmJqdDVQ1REhVfGgd1",
//         "is_local": false,
//         "name": "Wish You Were Here",
//         "popularity": 77,
//         "preview_url": "https://p.scdn.co/mp3-preview/7ce0d4e5f0ffcf8fe1a312c9c2f9331c8d2bf994?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 4,
//         "type": "track",
//         "uri": "spotify:track:6mFkJmJqdDVQ1REhVfGgd1"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/5Dbax7G8SWrP9xyzkOvy2F"
//           },
//           "href": "https://api.spotify.com/v1/albums/5Dbax7G8SWrP9xyzkOvy2F",
//           "id": "5Dbax7G8SWrP9xyzkOvy2F",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/61fbfc12c92752d2334547c00d5f13b8b7edba94",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/464f49ec36104a5939ea76cf1597a5311d91f602",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/1e8320282c222089439b3b775008fde1080efde8",
//               "width": 64
//             }
//           ],
//           "name": "The Wall",
//           "release_date": "1979-11-30",
//           "release_date_precision": "day",
//           "total_tracks": 26,
//           "type": "album",
//           "uri": "spotify:album:5Dbax7G8SWrP9xyzkOvy2F"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 2,
//         "duration_ms": 382296,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100113"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/5HNCy40Ni5BZJFw1TKzRsC"
//         },
//         "href": "https://api.spotify.com/v1/tracks/5HNCy40Ni5BZJFw1TKzRsC",
//         "id": "5HNCy40Ni5BZJFw1TKzRsC",
//         "is_local": false,
//         "name": "Comfortably Numb",
//         "popularity": 75,
//         "preview_url": "https://p.scdn.co/mp3-preview/daf1a7a5cf0ca8fc212ce61ac3d058fb12e2814f?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 6,
//         "type": "track",
//         "uri": "spotify:track:5HNCy40Ni5BZJFw1TKzRsC"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/5Dbax7G8SWrP9xyzkOvy2F"
//           },
//           "href": "https://api.spotify.com/v1/albums/5Dbax7G8SWrP9xyzkOvy2F",
//           "id": "5Dbax7G8SWrP9xyzkOvy2F",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/61fbfc12c92752d2334547c00d5f13b8b7edba94",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/464f49ec36104a5939ea76cf1597a5311d91f602",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/1e8320282c222089439b3b775008fde1080efde8",
//               "width": 64
//             }
//           ],
//           "name": "The Wall",
//           "release_date": "1979-11-30",
//           "release_date_precision": "day",
//           "total_tracks": 26,
//           "type": "album",
//           "uri": "spotify:album:5Dbax7G8SWrP9xyzkOvy2F"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 238746,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100099"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/4gMgiXfqyzZLMhsksGmbQV"
//         },
//         "href": "https://api.spotify.com/v1/tracks/4gMgiXfqyzZLMhsksGmbQV",
//         "id": "4gMgiXfqyzZLMhsksGmbQV",
//         "is_local": false,
//         "name": "Another Brick in the Wall, Pt. 2",
//         "popularity": 77,
//         "preview_url": "https://p.scdn.co/mp3-preview/92210b01fcc6efa80008663c158baf79cf0d7b5f?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 5,
//         "type": "track",
//         "uri": "spotify:track:4gMgiXfqyzZLMhsksGmbQV"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 382834,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100081"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/0vFOzaXqZHahrZp6enQwQb"
//         },
//         "href": "https://api.spotify.com/v1/tracks/0vFOzaXqZHahrZp6enQwQb",
//         "id": "0vFOzaXqZHahrZp6enQwQb",
//         "is_local": false,
//         "name": "Money",
//         "popularity": 74,
//         "preview_url": "https://p.scdn.co/mp3-preview/eceb1b928c7339ba16bfde8c4f9731af72ee1637?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 6,
//         "type": "track",
//         "uri": "spotify:track:0vFOzaXqZHahrZp6enQwQb"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 413947,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100079"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/3TO7bbrUKrOSPGRTB5MeCz"
//         },
//         "href": "https://api.spotify.com/v1/tracks/3TO7bbrUKrOSPGRTB5MeCz",
//         "id": "3TO7bbrUKrOSPGRTB5MeCz",
//         "is_local": false,
//         "name": "Time",
//         "popularity": 71,
//         "preview_url": "https://p.scdn.co/mp3-preview/83c1f92586bfa2a326b3c7c69aeb9321007f5055?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 4,
//         "type": "track",
//         "uri": "spotify:track:3TO7bbrUKrOSPGRTB5MeCz"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 169534,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100077"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/2ctvdKmETyOzPb2GiJJT53"
//         },
//         "href": "https://api.spotify.com/v1/tracks/2ctvdKmETyOzPb2GiJJT53",
//         "id": "2ctvdKmETyOzPb2GiJJT53",
//         "is_local": false,
//         "name": "Breathe (In the Air)",
//         "popularity": 69,
//         "preview_url": "https://p.scdn.co/mp3-preview/3453f7f075272cbb77f09ba0e50914b55c07cedc?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 2,
//         "type": "track",
//         "uri": "spotify:track:2ctvdKmETyOzPb2GiJJT53"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/5Dbax7G8SWrP9xyzkOvy2F"
//           },
//           "href": "https://api.spotify.com/v1/albums/5Dbax7G8SWrP9xyzkOvy2F",
//           "id": "5Dbax7G8SWrP9xyzkOvy2F",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/61fbfc12c92752d2334547c00d5f13b8b7edba94",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/464f49ec36104a5939ea76cf1597a5311d91f602",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/1e8320282c222089439b3b775008fde1080efde8",
//               "width": 64
//             }
//           ],
//           "name": "The Wall",
//           "release_date": "1979-11-30",
//           "release_date_precision": "day",
//           "total_tracks": 26,
//           "type": "album",
//           "uri": "spotify:album:5Dbax7G8SWrP9xyzkOvy2F"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 2,
//         "duration_ms": 278440,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100108"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/7F02x6EKYIQV3VcTaTm7oN"
//         },
//         "href": "https://api.spotify.com/v1/tracks/7F02x6EKYIQV3VcTaTm7oN",
//         "id": "7F02x6EKYIQV3VcTaTm7oN",
//         "is_local": false,
//         "name": "Hey You",
//         "popularity": 69,
//         "preview_url": "https://p.scdn.co/mp3-preview/a03fcdbf2223e1fe78f886770b0797553b924fc6?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 1,
//         "type": "track",
//         "uri": "spotify:track:7F02x6EKYIQV3VcTaTm7oN"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 226666,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100140"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/05uGBKRCuePsf43Hfm0JwX"
//         },
//         "href": "https://api.spotify.com/v1/tracks/05uGBKRCuePsf43Hfm0JwX",
//         "id": "05uGBKRCuePsf43Hfm0JwX",
//         "is_local": false,
//         "name": "Brain Damage",
//         "popularity": 66,
//         "preview_url": "https://p.scdn.co/mp3-preview/6e7066dc0fa4173ec9ee83b17953095de076faa1?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 9,
//         "type": "track",
//         "uri": "spotify:track:05uGBKRCuePsf43Hfm0JwX"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 469224,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100082"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/1TKTiKp3zbNgrBH2IwSwIx"
//         },
//         "href": "https://api.spotify.com/v1/tracks/1TKTiKp3zbNgrBH2IwSwIx",
//         "id": "1TKTiKp3zbNgrBH2IwSwIx",
//         "is_local": false,
//         "name": "Us and Them",
//         "popularity": 66,
//         "preview_url": "https://p.scdn.co/mp3-preview/021c52015787b3b1a75ca64d41a034c52119c677?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 7,
//         "type": "track",
//         "uri": "spotify:track:1TKTiKp3zbNgrBH2IwSwIx"
//       },
//       {
//         "album": {
//           "album_type": "album",
//           "artists": [
//             {
//               "external_urls": {
//                 "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//               },
//               "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//               "id": "0k17h0D3J5VfsdmQ1iZtE9",
//               "name": "Pink Floyd",
//               "type": "artist",
//               "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//             }
//           ],
//           "available_markets": [
//             "AD",
//             "AE",
//             "AR",
//             "AT",
//             "AU",
//             "BE",
//             "BG",
//             "BH",
//             "BO",
//             "BR",
//             "CA",
//             "CH",
//             "CL",
//             "CO",
//             "CR",
//             "CY",
//             "CZ",
//             "DE",
//             "DK",
//             "DO",
//             "DZ",
//             "EC",
//             "EE",
//             "EG",
//             "ES",
//             "FI",
//             "FR",
//             "GB",
//             "GR",
//             "GT",
//             "HK",
//             "HN",
//             "HU",
//             "ID",
//             "IE",
//             "IL",
//             "IN",
//             "IS",
//             "IT",
//             "JO",
//             "JP",
//             "KW",
//             "LB",
//             "LI",
//             "LT",
//             "LU",
//             "LV",
//             "MA",
//             "MC",
//             "MT",
//             "MX",
//             "MY",
//             "NI",
//             "NL",
//             "NO",
//             "NZ",
//             "OM",
//             "PA",
//             "PE",
//             "PH",
//             "PL",
//             "PS",
//             "PT",
//             "PY",
//             "QA",
//             "RO",
//             "SA",
//             "SE",
//             "SG",
//             "SK",
//             "SV",
//             "TH",
//             "TN",
//             "TR",
//             "TW",
//             "US",
//             "UY",
//             "VN",
//             "ZA"
//           ],
//           "external_urls": {
//             "spotify": "https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv"
//           },
//           "href": "https://api.spotify.com/v1/albums/4LH4d3cOWNNsVw41Gqt2kv",
//           "id": "4LH4d3cOWNNsVw41Gqt2kv",
//           "images": [
//             {
//               "height": 640,
//               "url": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
//               "width": 640
//             },
//             {
//               "height": 300,
//               "url": "https://i.scdn.co/image/00a613ea9cf34c561cb5bb4cd62c4bbf907853e3",
//               "width": 300
//             },
//             {
//               "height": 64,
//               "url": "https://i.scdn.co/image/c4bb8e18b0207c41d9fa1becd4fca1b6f68c06e6",
//               "width": 64
//             }
//           ],
//           "name": "The Dark Side of the Moon",
//           "release_date": "1973-03-01",
//           "release_date_precision": "day",
//           "total_tracks": 10,
//           "type": "album",
//           "uri": "spotify:album:4LH4d3cOWNNsVw41Gqt2kv"
//         },
//         "artists": [
//           {
//             "external_urls": {
//               "spotify": "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
//             },
//             "href": "https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9",
//             "id": "0k17h0D3J5VfsdmQ1iZtE9",
//             "name": "Pink Floyd",
//             "type": "artist",
//             "uri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9"
//           }
//         ],
//         "available_markets": [
//           "AD",
//           "AE",
//           "AR",
//           "AT",
//           "AU",
//           "BE",
//           "BG",
//           "BH",
//           "BO",
//           "BR",
//           "CA",
//           "CH",
//           "CL",
//           "CO",
//           "CR",
//           "CY",
//           "CZ",
//           "DE",
//           "DK",
//           "DO",
//           "DZ",
//           "EC",
//           "EE",
//           "EG",
//           "ES",
//           "FI",
//           "FR",
//           "GB",
//           "GR",
//           "GT",
//           "HK",
//           "HN",
//           "HU",
//           "ID",
//           "IE",
//           "IL",
//           "IN",
//           "IS",
//           "IT",
//           "JO",
//           "JP",
//           "KW",
//           "LB",
//           "LI",
//           "LT",
//           "LU",
//           "LV",
//           "MA",
//           "MC",
//           "MT",
//           "MX",
//           "MY",
//           "NI",
//           "NL",
//           "NO",
//           "NZ",
//           "OM",
//           "PA",
//           "PE",
//           "PH",
//           "PL",
//           "PS",
//           "PT",
//           "PY",
//           "QA",
//           "RO",
//           "SA",
//           "SE",
//           "SG",
//           "SK",
//           "SV",
//           "TH",
//           "TN",
//           "TR",
//           "TW",
//           "US",
//           "UY",
//           "VN",
//           "ZA"
//         ],
//         "disc_number": 1,
//         "duration_ms": 283872,
//         "explicit": false,
//         "external_ids": {
//           "isrc": "GBN9Y1100080"
//         },
//         "external_urls": {
//           "spotify": "https://open.spotify.com/track/2TjdnqlpwOjhijHCwHCP2d"
//         },
//         "href": "https://api.spotify.com/v1/tracks/2TjdnqlpwOjhijHCwHCP2d",
//         "id": "2TjdnqlpwOjhijHCwHCP2d",
//         "is_local": false,
//         "name": "The Great Gig in the Sky",
//         "popularity": 67,
//         "preview_url": "https://p.scdn.co/mp3-preview/94d312ff335e2a0d63c1b4623d739d9c1f95ced9?cid=774b29d4f13844c495f206cafdad9c86",
//         "track_number": 5,
//         "type": "track",
//         "uri": "spotify:track:2TjdnqlpwOjhijHCwHCP2d"
//       }
//     ],
//     "limit": 10,
//     "next": "https://api.spotify.com/v1/search?query=pink+floyd&type=track&market=US&offset=10&limit=10",
//     "offset": 0,
//     "previous": null,
//     "total": 3915
//   }
// }`);

export default Spotify;
